/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/search/courses": {
    /** Search for courses */
    post: {
      parameters: {
        query: {
          /** @description Search Query */
          q: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["model.CourseSearchResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
          };
        };
        /** @description Not Found */
        404: {
          content: {
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
          };
        };
      };
    };
  };
  "/search/universities": {
    /** Search for universities */
    post: {
      parameters: {
        query: {
          /** @description Search Query */
          q: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["model.UniversitySearchResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
          };
        };
        /** @description Not Found */
        404: {
          content: {
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
          };
        };
      };
    };
  };
  "/universities": {
    /** Get Universities */
    get: {
      parameters: {
        query?: {
          page?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              totalPages: number;
              items: components["schemas"]["model.UniversityPreview"][];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
          };
        };
        /** @description Not Found */
        404: {
          content: {
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
          };
        };
      };
    };
    /** Create new University */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            name: string;
            nameShort: string;
            country: string;
            city: string;
            language: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["model.UniversityPreview"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
          };
        };
        /** @description Not Found */
        404: {
          content: {
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
          };
        };
      };
    };
  };
  "/universities/{universityId}": {
    /**
     * Get specific University
     * @description retrieve meta data for a university including courses
     */
    get: {
      parameters: {
        path: {
          universityId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["model.University"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
          };
        };
        /** @description Not Found */
        404: {
          content: {
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
          };
        };
      };
    };
  };
  "/universities/{universityId}/courses": {
    /** Create new Course for University */
    post: {
      parameters: {
        path: {
          universityId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            name: string;
            nameShort: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["model.CoursePreview"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
          };
        };
        /** @description Not Found */
        404: {
          content: {
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
          };
        };
      };
    };
  };
  "/courses/{courseId}": {
    /** Get a specific course */
    get: {
      parameters: {
        path: {
          courseId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["model.Course"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
          };
        };
        /** @description Not Found */
        404: {
          content: {
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
          };
        };
      };
    };
  };
  "/courses/{courseId}/documents": {
    /** Get documents for a specific course */
    get: {
      parameters: {
        path: {
          courseId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["model.Document"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
          };
        };
        /** @description Not Found */
        404: {
          content: {
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
          };
        };
      };
    };
    /**
     * Push a new Document
     * @description Push a new document to the courses
     */
    post: {
      parameters: {
        query: {
          name: string;
        };
        path: {
          courseId: string;
        };
      };
      requestBody?: {
        content: {
          "application/pdf": string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["model.Document"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
          };
        };
        /** @description Not Found */
        404: {
          content: {
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "model.CourseSearchResult": {
      query: string;
      limit: number;
      processingTimeMs: number;
      hits: components["schemas"]["model.CourseSearchPreview"][];
    };
    "model.UniversitySearchResult": {
      query: string;
      limit: number;
      processingTimeMs: number;
      hits: components["schemas"]["model.UniversitySearchPreview"][];
    };
    "model.UniversityPreview": {
      /** Format: uuid */
      id: string;
      name: string;
      nameShort: string;
      country: string;
      city: string;
      language: string;
    };
    "model.University": components["schemas"]["model.UniversityPreview"] & {
      courses: components["schemas"]["model.CoursePreview"][];
    };
    "model.CoursePreview": {
      /** Format: uuid */
      id: string;
      name: string;
      nameShort: string;
    };
    "model.Course": components["schemas"]["model.CoursePreview"] & {
      university: components["schemas"]["model.CourseUniversityPreview"];
    };
    "model.CourseUniversityPreview": {
      /** Format: uuid */
      id: string;
      name: string;
      nameShort: string;
    };
    "model.CourseSearchPreview": {
      /** Format: uuid */
      id: string;
      title: string;
      nameShort: string;
      universityId: string;
      universityName: string;
      universityNameShort: string;
      universityCountry: string;
    };
    "model.UniversitySearchPreview": {
      title: string;
      /** Format: uuid */
      id: string;
      nameShort: string;
      country: string;
    };
    "model.Document": {
      title: string;
      fileUrl: string;
      thumbUrl: string;
      tag: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
