// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateCoursesParams struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UniversityID pgtype.UUID
	Name         string
}

type CreateDocumentsParams struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	Title        string
	ThumbnailUrl string
	FileUrl      string
	Tag          string
	CourseID     pgtype.UUID
}

type CreateUniversitiesParams struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Name      string
}
