// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ModelCourse defines model for model.Course.
type ModelCourse struct {
	Id         openapi_types.UUID           `json:"id"`
	Name       string                       `json:"name"`
	NameShort  string                       `json:"nameShort"`
	University ModelCourseUniversityPreview `json:"university"`
}

// ModelCoursePreview defines model for model.CoursePreview.
type ModelCoursePreview struct {
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	NameShort string             `json:"nameShort"`
}

// ModelCourseUniversityPreview defines model for model.CourseUniversityPreview.
type ModelCourseUniversityPreview struct {
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	NameShort string             `json:"nameShort"`
}

// ModelDocument defines model for model.Document.
type ModelDocument struct {
	FileUrl  string `json:"fileUrl"`
	Tag      string `json:"tag"`
	ThumbUrl string `json:"thumbUrl"`
	Title    string `json:"title"`
}

// ModelUniversity defines model for model.University.
type ModelUniversity struct {
	City      string               `json:"city"`
	Country   string               `json:"country"`
	Courses   []ModelCoursePreview `json:"courses"`
	Id        openapi_types.UUID   `json:"id"`
	Language  string               `json:"language"`
	Name      string               `json:"name"`
	NameShort string               `json:"nameShort"`
}

// ModelUniversityPreview defines model for model.UniversityPreview.
type ModelUniversityPreview struct {
	City      string             `json:"city"`
	Country   string             `json:"country"`
	Id        openapi_types.UUID `json:"id"`
	Language  string             `json:"language"`
	Name      string             `json:"name"`
	NameShort string             `json:"nameShort"`
}

// PostCoursesCourseIdDocumentsParams defines parameters for PostCoursesCourseIdDocuments.
type PostCoursesCourseIdDocumentsParams struct {
	Name string `form:"name" json:"name"`
}

// GetUniversitiesParams defines parameters for GetUniversities.
type GetUniversitiesParams struct {
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// PostUniversitiesJSONBody defines parameters for PostUniversities.
type PostUniversitiesJSONBody struct {
	City      string `json:"city"`
	Country   string `json:"country"`
	Language  string `json:"language"`
	Name      string `json:"name"`
	NameShort string `json:"nameShort"`
}

// PostUniversitiesUniversityIdCoursesJSONBody defines parameters for PostUniversitiesUniversityIdCourses.
type PostUniversitiesUniversityIdCoursesJSONBody struct {
	Name      string `json:"name"`
	NameShort string `json:"nameShort"`
}

// PostUniversitiesJSONRequestBody defines body for PostUniversities for application/json ContentType.
type PostUniversitiesJSONRequestBody PostUniversitiesJSONBody

// PostUniversitiesUniversityIdCoursesJSONRequestBody defines body for PostUniversitiesUniversityIdCourses for application/json ContentType.
type PostUniversitiesUniversityIdCoursesJSONRequestBody PostUniversitiesUniversityIdCoursesJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a specific course
	// (GET /courses/{courseId})
	GetCoursesCourseId(c *fiber.Ctx, courseId openapi_types.UUID) error
	// Get documents for a specific course
	// (GET /courses/{courseId}/documents)
	GetCoursesCourseIdDocuments(c *fiber.Ctx, courseId openapi_types.UUID) error
	// Push a new Document
	// (POST /courses/{courseId}/documents)
	PostCoursesCourseIdDocuments(c *fiber.Ctx, courseId openapi_types.UUID, params PostCoursesCourseIdDocumentsParams) error
	// Get all Universities
	// (GET /universities)
	GetUniversities(c *fiber.Ctx, params GetUniversitiesParams) error
	// Create new University
	// (POST /universities)
	PostUniversities(c *fiber.Ctx) error
	// Get specific University
	// (GET /universities/{universityId})
	GetUniversitiesUniversityId(c *fiber.Ctx, universityId openapi_types.UUID) error
	// Create new Course for University
	// (POST /universities/{universityId}/courses)
	PostUniversitiesUniversityIdCourses(c *fiber.Ctx, universityId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetCoursesCourseId operation middleware
func (siw *ServerInterfaceWrapper) GetCoursesCourseId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", c.Params("courseId"), &courseId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter courseId: %w", err).Error())
	}

	return siw.Handler.GetCoursesCourseId(c, courseId)
}

// GetCoursesCourseIdDocuments operation middleware
func (siw *ServerInterfaceWrapper) GetCoursesCourseIdDocuments(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", c.Params("courseId"), &courseId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter courseId: %w", err).Error())
	}

	return siw.Handler.GetCoursesCourseIdDocuments(c, courseId)
}

// PostCoursesCourseIdDocuments operation middleware
func (siw *ServerInterfaceWrapper) PostCoursesCourseIdDocuments(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", c.Params("courseId"), &courseId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter courseId: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostCoursesCourseIdDocumentsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "name" -------------

	if paramValue := c.Query("name"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument name is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "name", query, &params.Name)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter name: %w", err).Error())
	}

	return siw.Handler.PostCoursesCourseIdDocuments(c, courseId, params)
}

// GetUniversities operation middleware
func (siw *ServerInterfaceWrapper) GetUniversities(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUniversitiesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", query, &params.Search)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter search: %w", err).Error())
	}

	return siw.Handler.GetUniversities(c, params)
}

// PostUniversities operation middleware
func (siw *ServerInterfaceWrapper) PostUniversities(c *fiber.Ctx) error {

	return siw.Handler.PostUniversities(c)
}

// GetUniversitiesUniversityId operation middleware
func (siw *ServerInterfaceWrapper) GetUniversitiesUniversityId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "universityId" -------------
	var universityId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "universityId", c.Params("universityId"), &universityId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter universityId: %w", err).Error())
	}

	return siw.Handler.GetUniversitiesUniversityId(c, universityId)
}

// PostUniversitiesUniversityIdCourses operation middleware
func (siw *ServerInterfaceWrapper) PostUniversitiesUniversityIdCourses(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "universityId" -------------
	var universityId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "universityId", c.Params("universityId"), &universityId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter universityId: %w", err).Error())
	}

	return siw.Handler.PostUniversitiesUniversityIdCourses(c, universityId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(m)
	}

	router.Get(options.BaseURL+"/courses/:courseId", wrapper.GetCoursesCourseId)

	router.Get(options.BaseURL+"/courses/:courseId/documents", wrapper.GetCoursesCourseIdDocuments)

	router.Post(options.BaseURL+"/courses/:courseId/documents", wrapper.PostCoursesCourseIdDocuments)

	router.Get(options.BaseURL+"/universities", wrapper.GetUniversities)

	router.Post(options.BaseURL+"/universities", wrapper.PostUniversities)

	router.Get(options.BaseURL+"/universities/:universityId", wrapper.GetUniversitiesUniversityId)

	router.Post(options.BaseURL+"/universities/:universityId/courses", wrapper.PostUniversitiesUniversityIdCourses)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yYz27jNhDGX4WY9ihYbnd70a2bbYugQDdo4NMiB0Ya2VxIpDIcZmEYeveClCzrnxMb",
	"TXaTRS5BbHE+Dmd+/Eh5B6kpK6NRs4VkBzbdYCnDv6XJsFhcGEcW/WdZFJ9ySD7v4GfCHBL4KT7Exm1g",
	"3I+6IrxX+BXqaAcVmQqJFQZtp9U9klW89Z9O1Vt1UZ1yHQHhnVOEGSSf+7o3EfC2QkjA3H7BlKG+qSOY",
	"Sy8ZZ6cy/zc3VEqGBJxTGXRqlknpNdQRaFmGwsw+uN4Y4pmno4SDchDqh01zH2Y+LcRrWsNHk7oSNU+T",
	"zlWBKypmE2K5nv9+48rbo0GKC3x8Bc2wqJu/p9pMfHwxqwHJ5+yRGZon+yQN7W4ayljac3bLQXWfuySS",
	"28ni93M8tGFOAC5tSzDpQWqcZpp/diKlhdRrJ9fHSX0ehA+5R83yeplMq+U1lc6Nny1Dm5KqWBkNCVyz",
	"y7Y5IYrfry6ho3LyfShxiPhlsVws/RpMhVpWChJ4t1gu3kEEleRNKHjcNi7eNf9cZrX/eo1hvb410s9/",
	"mUECfyE3UNiLdmxQIlkiI9lArPITe/V9KRJID4MP1WJyGLUHxQndq298sK2MbkH+dbls0NbcmoCsqkKl",
	"Idv4i/UF2PX0zwZ/hvg6GrXk099+1PsmleGjDzIT/+KdQ8vNmPfTMf8YFn8apzM/4rc5lUvNSFoW4hrp",
	"Hkn8QWQocGddWUq/H3xXhBS2wlTlKhVNtRvHsYOd6cNm2h1nrZPaMxr/sYv5EQnozpbXxEDXRpEbepCI",
	"Q8O9N1fG8nTWK2c3QgqNXzthwUbwBsUeqGhEyZWxLwCTqJW+cxgst9Vubfm47ixuoXcfTLZ9gLQqy4eg",
	"dRneKi1DDmPt5uB4Y3mW5R55Xe7z7Ho/6+7q7QWi9a/htIRMCu9RyKIQg4ho6nSr4fM5bEdsWZSUeo4f",
	"oenbNHzuRviKTrKiEKMO7Fs/aFzfuaY2NFI4bSNPq/4Ed9Nnv3T+7/tm/Ybm42heEErGYEq9d7WjbI6d",
	"Kd4dflMY3rCPGFWJLEUmWbaH+SFcKJ0WLlN6ffQgHpnYqjf1SeewGwZ8vyvbOUS9aFfr7mJPAE/ce50/",
	"zQH7AFx0zHxrDp7Cgp/FML+zKT72O8uLN8RmAcGoZvHuvYB6iaDZMOeogAQ2zJWF+qb+LwAA//+S+drS",
	"RxYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
