// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PostCoursesCourseIdDocumentsParamsTag.
const (
	Exam     PostCoursesCourseIdDocumentsParamsTag = "exam"
	Exercise PostCoursesCourseIdDocumentsParamsTag = "exercise"
	Notes    PostCoursesCourseIdDocumentsParamsTag = "notes"
	Slides   PostCoursesCourseIdDocumentsParamsTag = "slides"
)

// ModelDocument defines model for model.Document.
type ModelDocument struct {
	FileUrl  string             `json:"fileUrl"`
	Id       openapi_types.UUID `json:"id"`
	Tag      string             `json:"tag"`
	ThumbUrl string             `json:"thumbUrl"`
	Title    string             `json:"title"`
}

// ModelUniversityPreview defines model for model.UniversityPreview.
type ModelUniversityPreview struct {
	Id    openapi_types.UUID `json:"id"`
	Title string             `json:"title"`
}

// PostCoursesCourseIdDocumentsParams defines parameters for PostCoursesCourseIdDocuments.
type PostCoursesCourseIdDocumentsParams struct {
	Name string                                `form:"name" json:"name"`
	Tag  PostCoursesCourseIdDocumentsParamsTag `form:"tag" json:"tag"`
}

// PostCoursesCourseIdDocumentsParamsTag defines parameters for PostCoursesCourseIdDocuments.
type PostCoursesCourseIdDocumentsParamsTag string

// GetUniversitiesParams defines parameters for GetUniversities.
type GetUniversitiesParams struct {
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get specific Document
	// (GET /courses/{courseId}/documents)
	GetCoursesCourseIdDocuments(c *fiber.Ctx, courseId openapi_types.UUID) error
	// Push a new Document
	// (POST /courses/{courseId}/documents)
	PostCoursesCourseIdDocuments(c *fiber.Ctx, courseId openapi_types.UUID, params PostCoursesCourseIdDocumentsParams) error
	// Get all Universities
	// (GET /universities)
	GetUniversities(c *fiber.Ctx, params GetUniversitiesParams) error
	// Get specific University
	// (GET /universities/{universityId})
	GetUniversitiesUniversityId(c *fiber.Ctx, universityId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetCoursesCourseIdDocuments operation middleware
func (siw *ServerInterfaceWrapper) GetCoursesCourseIdDocuments(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", c.Params("courseId"), &courseId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter courseId: %w", err).Error())
	}

	return siw.Handler.GetCoursesCourseIdDocuments(c, courseId)
}

// PostCoursesCourseIdDocuments operation middleware
func (siw *ServerInterfaceWrapper) PostCoursesCourseIdDocuments(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", c.Params("courseId"), &courseId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter courseId: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostCoursesCourseIdDocumentsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "name" -------------

	if paramValue := c.Query("name"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument name is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "name", query, &params.Name)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter name: %w", err).Error())
	}

	// ------------- Required query parameter "tag" -------------

	if paramValue := c.Query("tag"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument tag is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "tag", query, &params.Tag)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter tag: %w", err).Error())
	}

	return siw.Handler.PostCoursesCourseIdDocuments(c, courseId, params)
}

// GetUniversities operation middleware
func (siw *ServerInterfaceWrapper) GetUniversities(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUniversitiesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", query, &params.Search)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter search: %w", err).Error())
	}

	return siw.Handler.GetUniversities(c, params)
}

// GetUniversitiesUniversityId operation middleware
func (siw *ServerInterfaceWrapper) GetUniversitiesUniversityId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "universityId" -------------
	var universityId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "universityId", c.Params("universityId"), &universityId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter universityId: %w", err).Error())
	}

	return siw.Handler.GetUniversitiesUniversityId(c, universityId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(m)
	}

	router.Get(options.BaseURL+"/courses/:courseId/documents", wrapper.GetCoursesCourseIdDocuments)

	router.Post(options.BaseURL+"/courses/:courseId/documents", wrapper.PostCoursesCourseIdDocuments)

	router.Get(options.BaseURL+"/universities", wrapper.GetUniversities)

	router.Get(options.BaseURL+"/universities/:universityId", wrapper.GetUniversitiesUniversityId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWQW/zNgz9KwK3oxFn+75dfFvbbQgGbMGKnIocFItJVNiSS1FpjcD/fZDsOHGcptkO",
	"2wrsFNUiH5/0HqnuIbdlZQ0adpDtweVbLGVcllZhMXmwuS/RcPhSka2QWGPcX+sCF1SEJdcVQgaOSZsN",
	"NAloFSMslZIhA++1gmQcxnJzMZ23vly9h82aC7yw0yRA+OI1oYLsCdqKMTbpuZ5At9WXPSu7esacQ4H2",
	"4Aujd0hOcz0n3Gl8Hd/Araf8y4THrEKwNmsbYBS6nHTF2hrI4JG9qteEKH6cz3qE8fd4mJjx3WQ6mQZi",
	"tkIjKw0ZfJlMJ18ggUryNh4tza0nhy7dt4uZalLVWSEGbJDHXAiZNO5QSFEiSxEYh8vR1gi5sp6FFK7C",
	"XK91Lg5wEIlQjJopyOAX5Pu2+n1X+6GvHCiSLJGRHGRPe9ChbqANCRhZhpMfGMPp/TJ5TDp736BaswzJ",
	"rrLGtVp/P52Gn9wa7rpBVlWh80g7fXbh/PsTfM1YxsRvCdeQwTfpsdHSrsvSsxZrehqSSNat6sMb/v3X",
	"EPW1JTPcupNK/IEvHh23MV/HMb9ZFj9bb1SI+OESyswwkpGFeETaIYmfiCxFrzpflpLqVqCjjA9HGVlu",
	"gihwNMqySaCy7oJV5t5thRQGX3sjCLaCtyg66418MbfuP2CMpIN+8Uj1ETv+XMO9EScMpWswaHwZ7hjf",
	"ZBmyLMebcoVWcYFvSLl2pzNk6OlokDur6it2rtR66Ob+UlbayEj3HLudZv83zMWGOTH7B+3SJJD6w8vT",
	"PTMfjNqiEIOMC+N0Mdy/1ClnNnQoKQ+t876B/8EJOX6LP9OoDAqdKXCQfiDcWP103/9Vz1TzsRniq6sk",
	"S7G2JOTRGLXQJi+80mbz7nw9M8ripPRN49UPE/69t/dvGeozvLVH2lc8FNIjXiuUD/9Gw5a5ctAsmz8D",
	"AAD//+FlPv/xCwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
